#!/usr/bin/env python3
"""Mechanical PSL->read-only sorted C index. No runtime networking/dependencies."""
import argparse
import hashlib
from pathlib import Path

p = argparse.ArgumentParser()
p.add_argument("source", type=Path)
p.add_argument("output", type=Path)
a = p.parse_args()
raw = a.source.read_bytes()
rules = set()
for line in raw.decode("utf-8").splitlines():
    line = line.split("//", 1)[0].strip()
    if not line:
        continue
    prefix = ""
    if line.startswith("!"):
        prefix, line = "!", line[1:]
    elif line.startswith("*."):
        prefix, line = "*.", line[2:]
    rules.add(prefix + line.encode("idna").decode("ascii").lower())
if len(rules) < 1000:
    raise SystemExit("PSL is incomplete; refusing generated index")
blob = bytearray()
offsets = []
for rule in sorted(rules):
    offsets.append(len(blob))
    blob.extend(rule.encode("ascii") + b"\0")
out = ["/* Generated by scripts/build-psl-index.py. PSL MPL-2.0.",
       " * Source SHA256: " + hashlib.sha256(raw).hexdigest() + " */",
       "static const char d2k_psl_blob[] ="]
for i in range(0, len(blob), 48):
    out.append('    "' + ''.join('\\%03o' % c for c in blob[i:i+48]) + '"')
out[-1] += ";"
out.append("static const unsigned int d2k_psl_offsets[] = {")
for i in range(0, len(offsets), 16):
    out.append("    " + ",".join(map(str, offsets[i:i+16])) + ",")
out.append("};\n")
a.output.write_text("\n".join(out), encoding="ascii")
print(f"PSL {len(rules)} rules, {len(blob)} bytes + {len(offsets)*4} byte offsets")
